export const beverageCatalogSource =
  "Beverage inventory 2026.xlsx, latest usable stock snapshot from March 2026";

export const beverageSeedCategories = [
  {
    name: "Soft Drinks",
    slug: "soft-drinks",
    description: "Carbonated soft drinks, frozen beverages, and bottled soda variants from the 2026 beverage workbook.",
    sortOrder: 10,
  },
  {
    name: "Alcoholic Beverages",
    slug: "alcoholic-beverages",
    description: "Beer and ready-to-drink alcoholic beverages seeded from the 2026 beverage workbook.",
    sortOrder: 20,
  },
  {
    name: "Fruit Juices",
    slug: "fruit-juices",
    description: "Packaged juices and quenchers captured in the 2026 beverage workbook.",
    sortOrder: 30,
  },
  {
    name: "Energy Drinks",
    slug: "energy-drinks",
    description: "Energy and malt beverages tracked in the 2026 beverage workbook.",
    sortOrder: 40,
  },
  {
    name: "Water",
    slug: "water",
    description: "Still water and bottled water products from the 2026 beverage workbook.",
    sortOrder: 50,
  },
] as const;

export const beverageSeedProducts = [
  {
    categoryName: "Soft Drinks",
    name: "Mixed Icee 12oz",
    baseName: "Mixed Icee",
    sizeLabel: "12oz",
    slug: "mixed-icee-12oz",
    sku: "BEV-MIXED-ICEE-12OZ",
    description: "Frozen soft drink serving, 12oz size.",
    priceGyd: 300,
    stockQty: 34,
    lowStockThreshold: 7,
  },
  {
    categoryName: "Soft Drinks",
    name: "Mixed Icee 20oz",
    baseName: "Mixed Icee",
    sizeLabel: "20oz",
    slug: "mixed-icee-20oz",
    sku: "BEV-MIXED-ICEE-20OZ",
    description: "Frozen soft drink serving, 20oz size.",
    priceGyd: 400,
    stockQty: 12,
    lowStockThreshold: 6,
  },
  {
    categoryName: "Soft Drinks",
    name: "Coca-Cola 15oz",
    baseName: "Coca-Cola",
    sizeLabel: "15oz",
    slug: "coca-cola-15oz",
    sku: "BEV-COCA-COLA-15OZ",
    description: "Coca-Cola bottled soft drink, 15oz.",
    priceGyd: 300,
    stockQty: 34,
    lowStockThreshold: 9,
  },
  {
    categoryName: "Soft Drinks",
    name: "Coca-Cola 20oz",
    baseName: "Coca-Cola",
    sizeLabel: "20oz",
    slug: "coca-cola-20oz",
    sku: "BEV-COCA-COLA-20OZ",
    description: "Coca-Cola bottled soft drink, 20oz.",
    priceGyd: 400,
    stockQty: 38,
    lowStockThreshold: 6,
  },
  {
    categoryName: "Soft Drinks",
    name: "Coca-Cola 2L",
    baseName: "Coca-Cola",
    sizeLabel: "2L",
    slug: "coca-cola-2l",
    sku: "BEV-COCA-COLA-2L",
    description: "Coca-Cola family-size bottle, 2L.",
    priceGyd: 1000,
    stockQty: 1,
    lowStockThreshold: 4,
  },
  {
    categoryName: "Soft Drinks",
    name: "Coca-Cola 1L",
    baseName: "Coca-Cola",
    sizeLabel: "1L",
    slug: "coca-cola-1l",
    sku: "BEV-COCA-COLA-1L",
    description: "Coca-Cola bottle, 1L size.",
    priceGyd: 500,
    stockQty: 8,
    lowStockThreshold: 4,
  },
  {
    categoryName: "Soft Drinks",
    name: "Icee 1L",
    baseName: "Icee",
    sizeLabel: "1L",
    slug: "icee-1l",
    sku: "BEV-ICEE-1L",
    description: "Icee bottled drink, 1L size.",
    priceGyd: 500,
    stockQty: 0,
    lowStockThreshold: 4,
  },
  {
    categoryName: "Soft Drinks",
    name: "Canada Dry Can",
    baseName: "Canada Dry",
    sizeLabel: "Can",
    slug: "canada-dry-can",
    sku: "BEV-CANADA-DRY-CAN",
    description: "Canada Dry canned soft drink.",
    priceGyd: 300,
    stockQty: 14,
    lowStockThreshold: 6,
  },
  {
    categoryName: "Alcoholic Beverages",
    name: "Shandy",
    baseName: "Shandy",
    sizeLabel: null,
    slug: "shandy",
    sku: "BEV-SHANDY",
    description: "Packaged shandy beverage.",
    priceGyd: 400,
    stockQty: 20,
    lowStockThreshold: 6,
  },
  {
    categoryName: "Alcoholic Beverages",
    name: "GT Beer",
    baseName: "GT Beer",
    sizeLabel: null,
    slug: "gt-beer",
    sku: "BEV-GT-BEER",
    description: "GT branded beer.",
    priceGyd: 400,
    stockQty: 48,
    lowStockThreshold: 12,
  },
  {
    categoryName: "Alcoholic Beverages",
    name: "Banks Beer",
    baseName: "Banks Beer",
    sizeLabel: null,
    slug: "banks-beer",
    sku: "BEV-BANKS-BEER",
    description: "Banks bottled beer.",
    priceGyd: 500,
    stockQty: 100,
    lowStockThreshold: 12,
  },
  {
    categoryName: "Alcoholic Beverages",
    name: "Guinness",
    baseName: "Guinness",
    sizeLabel: null,
    slug: "guinness",
    sku: "BEV-GUINNESS",
    description: "Guinness stout.",
    priceGyd: 500,
    stockQty: 8,
    lowStockThreshold: 12,
  },
  {
    categoryName: "Alcoholic Beverages",
    name: "Heineken",
    baseName: "Heineken",
    sizeLabel: null,
    slug: "heineken",
    sku: "BEV-HEINEKEN",
    description: "Heineken beer.",
    priceGyd: 700,
    stockQty: 0,
    lowStockThreshold: 4,
  },
  {
    categoryName: "Alcoholic Beverages",
    name: "Stag Beer",
    baseName: "Stag Beer",
    sizeLabel: null,
    slug: "stag-beer",
    sku: "BEV-STAG-BEER",
    description: "Stag branded beer.",
    priceGyd: 700,
    stockQty: 0,
    lowStockThreshold: 4,
  },
  {
    categoryName: "Alcoholic Beverages",
    name: "Itapava",
    baseName: "Itapava",
    sizeLabel: null,
    slug: "itapava",
    sku: "BEV-ITAPAVA",
    description: "Itapava beer.",
    priceGyd: 400,
    stockQty: 10,
    lowStockThreshold: 12,
  },
  {
    categoryName: "Fruit Juices",
    name: "Fruta Can",
    baseName: "Fruta",
    sizeLabel: "Can",
    slug: "fruta-can",
    sku: "BEV-FRUTA-CAN",
    description: "Fruta canned juice.",
    priceGyd: 300,
    stockQty: 24,
    lowStockThreshold: 8,
  },
  {
    categoryName: "Fruit Juices",
    name: "Quenchers Medium",
    baseName: "Quenchers",
    sizeLabel: "Medium",
    slug: "quenchers-medium",
    sku: "BEV-QUENCHERS-MEDIUM",
    description: "Quenchers juice, medium size.",
    priceGyd: 300,
    stockQty: 10,
    lowStockThreshold: 4,
  },
  {
    categoryName: "Fruit Juices",
    name: "Quenchers Small",
    baseName: "Quenchers",
    sizeLabel: "Small",
    slug: "quenchers-small",
    sku: "BEV-QUENCHERS-SMALL",
    description: "Quenchers juice, small size.",
    priceGyd: 300,
    stockQty: 0,
    lowStockThreshold: 5,
  },
  {
    categoryName: "Energy Drinks",
    name: "XL Can",
    baseName: "XL",
    sizeLabel: "Can",
    slug: "xl-can",
    sku: "BEV-XL-CAN",
    description: "XL canned energy drink.",
    priceGyd: 300,
    stockQty: 0,
    lowStockThreshold: 10,
  },
  {
    categoryName: "Energy Drinks",
    name: "Rude Boy",
    baseName: "Rude Boy",
    sizeLabel: null,
    slug: "rude-boy",
    sku: "BEV-RUDE-BOY",
    description: "Rude Boy energy drink.",
    priceGyd: 600,
    stockQty: 0,
    lowStockThreshold: 4,
  },
  {
    categoryName: "Energy Drinks",
    name: "Turbo 15oz",
    baseName: "Turbo",
    sizeLabel: "15oz",
    slug: "turbo-15oz",
    sku: "BEV-TURBO-15OZ",
    description: "Turbo energy drink, 15oz.",
    priceGyd: 300,
    stockQty: 6,
    lowStockThreshold: 5,
  },
  {
    categoryName: "Energy Drinks",
    name: "VitaMalt",
    baseName: "VitaMalt",
    sizeLabel: null,
    slug: "vitamalt",
    sku: "BEV-VITAMALT",
    description: "VitaMalt malt beverage.",
    priceGyd: 400,
    stockQty: 24,
    lowStockThreshold: 5,
  },
  {
    categoryName: "Energy Drinks",
    name: "Smalta",
    baseName: "Smalta",
    sizeLabel: null,
    slug: "smalta",
    sku: "BEV-SMALTA",
    description: "Smalta malt beverage.",
    priceGyd: 300,
    stockQty: 0,
    lowStockThreshold: 4,
  },
  {
    categoryName: "Water",
    name: "Small Water 20oz",
    baseName: "Small Water",
    sizeLabel: "20oz",
    slug: "small-water-20oz",
    sku: "BEV-SMALL-WATER-20OZ",
    description: "Small bottled water, 20oz.",
    priceGyd: 200,
    stockQty: 70,
    lowStockThreshold: 12,
  },
  {
    categoryName: "Water",
    name: "Large Water 1L",
    baseName: "Large Water",
    sizeLabel: "1L",
    slug: "large-water-1l",
    sku: "BEV-LARGE-WATER-1L",
    description: "Large bottled water, 1L.",
    priceGyd: 300,
    stockQty: 0,
    lowStockThreshold: 4,
  },
  {
    categoryName: "Water",
    name: "Splash Water",
    baseName: "Splash Water",
    sizeLabel: null,
    slug: "splash-water",
    sku: "BEV-SPLASH-WATER",
    description: "Splash branded bottled water.",
    priceGyd: 300,
    stockQty: 0,
    lowStockThreshold: 4,
  },
] as const;

export const skippedWorkbookItems = [
  "Quenchers Extra",
  "New Energy Drink",
  "Red Bull",
  "Lucozade",
] as const;
